version: '2.1'
services:

  configserver:
    image: maruftuhin/configserver:0.0.1-SNAPSHOT
    build: .
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"

  eurekaserver:
    image: maruftuhin/eurekaserver:0.0.1-SNAPSHOT
    build: .
    ports:
      - "8070:8070"
    depends_on:
      - configserver

  gatewayserver:
    image: maruftuhin/gatewayserver:0.0.1-SNAPSHOT
    build: .
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://configserver:8071"
      EUREKASERVER_URI: "http://eurekaserver:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      - configserver
      - eurekaserver

  licensingservice:
    image: maruftuhin/licensing-service:0.0.3-SNAPSHOT
    build: .
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
    ports:
      - "8080:8080"

  organizationservice:
    image: maruftuhin/organization-service:0.0.1-SNAPSHOT
    build: .
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      - configserver
    ports:
      - "8081:8081"
