apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kube\kompose\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: organizationservice
  name: organizationservice
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: organizationservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Tools\Kube\kompose\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: organizationservice
    spec:
      containers:
        - env:
            - name: CONFIGSERVER_PORT
              value: "8071"
            - name: CONFIGSERVER_URI
              value: http://configserver:8071
            - name: DATABASESERVER_PORT
              value: "5432"
            - name: ENCRYPT_KEY
              value: IMSYMMETRIC
            - name: PROFILE
              value: dev
          image: maruftuhin/organization-service:0.0.1-SNAPSHOT
          name: organizationservice
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
