apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Tools\Kube\kompose\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: organizationservice
  name: organizationservice
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: organizationservice
